---
version: '3.9'

x-pg: &postgres
  image: postgres:13.2
  environment:
    POSTGRES_DB: database
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  healthcheck:
    test: pg_isready -U admin -d database
    interval: 10s
    timeout: 3s

x-redis: &redis
  image: redis:7-alpine
  command: [ "sh", "-c", "redis-server --appendonly yes --requirepass admin" ]
  environment:
    REDIS_PASSWORD: ${REDIS_PASSWORD}
  healthcheck:
    test: redis-cli ping
    interval: 1s
    timeout: 10s
    retries: 10
    start_period: 5s

services:
  keycloak-postgres: 
    <<: *postgres
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    depends_on:
      - keycloak-postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-postgres
      DB_DATABASE: database
      DB_USER: admin
      PROXY_ADDRESS_FORWARDING: true
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      VIRTUAL_HOST: keycloak.fai.rezel.net
      LETSENCRYPT_HOST: keycloak.fai.rezel.net
      VIRTUAL_PORT: 8080
    healthcheck:
      timeout: 3s
      interval: 1s
      start_period: 150s # thibaud : démarre en 37s chez moi
      test: "curl -f http://localhost:8080/auth/ || exit 1"
    ports:
      - "127.0.0.1:8080:8080"    
    networks:
      - default
      - reverse_keycloak

  postgres:
    <<: *postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: nette
    ports:
      - "127.0.0.1:8003:8080"

volumes:
  keycloak-postgres:
  postgres:

networks:
  reverse_keycloak:
    external: true
