---
version: '3.9'

x-pg: &postgres
  image: postgres:13.2
  environment:
    POSTGRES_DB: database
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
  healthcheck:
    test: pg_isready -U admin -d database
    interval: 10s
    timeout: 3s

x-redis: &redis
  image: redis:7-alpine
  command: [ "sh", "-c", "redis-server --appendonly yes --requirepass admin" ]
  environment:
    REDIS_PASSWORD: admin
  healthcheck:
    test: redis-cli ping
    interval: 1s
    timeout: 10s
    retries: 10
    start_period: 5s


services:
  keycloak-postgres: *postgres
  keycloak:
    image: jboss/keycloak:latest
    depends_on:
      - keycloak-postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-postgres
      DB_DATABASE: database
      DB_USER: admin
      DB_PASSWORD: admin
    healthcheck:
      timeout: 3s
      interval: 1s
      start_period: 300s # thibaud : démarre en 37s chez moi
      test: "curl -f http://localhost:8080/auth/ || exit 1"
    ports:
      - "8080:8080"

  netbox-redis: *redis
  netbox-postgres: *postgres
  netbox:
    image: dbdc0c4053cc14f76a38aad7fd5d1ec9901f9b30a76ae63c342dc07c7bffb3c6
    depends_on:
      - netbox-postgres
    volumes:
    - netbox-media-files:/opt/netbox/netbox/media
    environment:
      DB_HOST: netbox-postgres
      DB_NAME: database
      DB_PASSWORD: admin
      DB_USER: admin
      REDIS_PASSWORD: admin
      REDIS_HOST: netbox-redis
      SKIP_SUPERUSER: false
      SUPERUSER_API_TOKEN: token
      SUPERUSER_EMAIL: admin@faipp.net
      SUPERUSER_NAME: admin
      SUPERUSER_PASSWORD: admin
      SECRET_KEY: changemeinprod
    ports:
      - "8002:8080"
    healthcheck:
      timeout: 3s
      interval: 1s
      start_period: 300s # thibaud : démarre en 190s chez moi
      test: "curl -f http://localhost:8080/ || exit 1"

  postgres:
    <<: *postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: nette
    ports:
      - "8003:8080"

volumes:
  netbox-media-files:
    driver: local
