apiVersion: apps/v1
kind: Deployment
metadata:
  name: sadh-front-deployment
  labels:
    app: sadh
    tier: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sadh
      tier: front
  template:
    metadata:
      labels:
        app: sadh
        tier: front
    spec:
      serviceAccountName: sadh-front-ksa
      containers:
      - name: sadh-front-container
        image: $FRONT_IMAGE_TAG
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: DEPLOY_ENV
          value: "${DEPLOY_ENV}"
      imagePullSecrets:
       - name: gitlab-registery-credentials
