---
apiVersion: v1
kind: Service
metadata:
  name: sadh-front-service
  namespace: default
  annotations:
    kube-vip.io/loadbalancerIPs: 137.194.15.36
spec:
  type: LoadBalancer
  selector:
    app: sadh
    tier: front
  loadBalancerClass: kube-vip.io/kube-vip-class
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sadh-front-service
  namespace: dev
  annotations:
    kube-vip.io/loadbalancerIPs: 137.194.15.36
spec:
  type: LoadBalancer
  selector:
    app: sadh
    tier: front
  loadBalancerClass: kube-vip.io/kube-vip-class
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 80
